# Generated by Django 5.2.7 on 2025-10-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlowersShop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='flower',
        ),
        migrations.AddField(
            model_name='supplier',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
