# Generated by Django 5.2.7 on 2025-10-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlowersShop', '0002_remove_order_user_remove_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='price',
            field=models.FloatField(),
        ),
    ]
